export type OrderListResponse = {
    _id: string
    orderNumber: string
    didNo: string
    // batchNo: string
    inOutBound: string
    incomingCallerNo: string
    mobileNo: string
    deliveryCharges: number
    discount: number
    total: number
    countryId: string
    stateId: string
    districtId: string
    tehsilId: string
    schemeId: string
    pincodeId: string
    areaId: string
    expectedDeliveryDate: string
    profileDeliveredBy: string
    complaintDetails: string
    complaintNo: string
    agentName: string
    name: string
    age: string
    address: string
    realtion: string
    agentDistrictId: string
    landmark: string
    alternateNo1: string
    watsappNo: string
    gender: string
    prepaid: string
    emailId: string
    channelId: string
    remark: string
    dispositionLevelTwoId: string
    dispositionLevelThreeId: string
    isDeleted: boolean
    isActive: boolean
    createdAt: string
    updatedAt: string
    __v: number
    schemeLabel: string
    schemeCode: string
    channelLabel: string
}
